# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-21 11:55
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('description', models.TextField(max_length=1000, verbose_name='\u7b80\u4ecb')),
                ('content', DjangoUeditor.models.UEditorField(max_length=200000, verbose_name='\u5185\u5bb9')),
                ('date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7814\u7a76\u8d44\u8baf\u5173\u952e\u8bcd',
                'verbose_name_plural': '\u7814\u7a76\u8d44\u8baf\u5173\u952e\u8bcd',
            },
        ),
    ]
