# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-22 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u5b57')),
                ('phone', models.CharField(max_length=11, verbose_name='\u7535\u8bdd')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='\u90ae\u7bb1')),
                ('comment', models.TextField(max_length=50000, verbose_name='\u8bc4\u8bba')),
                ('isRead', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u8bfb')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u63d0\u4ea4\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u63d0\u4ea4\u4fe1\u606f',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u6587\u7ae0', 'verbose_name_plural': '\u6587\u7ae0'},
        ),
    ]
