# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-25 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import index.util


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180322_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=index.util.upload_video_cover, verbose_name='\u4e0a\u4f20\u89c6\u9891\uff0c\u8981\u6c42mp4\u683c\u5f0f')),
                ('description', models.CharField(max_length=1000, verbose_name='\u89c6\u9891\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u89c6\u9891',
                'verbose_name_plural': '\u89c6\u9891',
            },
        ),
    ]
