# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-25 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spider_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=1000, verbose_name='\u5173\u952e\u8bcd\uff08\u82f1\u6587\u9017\u53f7\u5206\u9694\uff0c\u522b\u8d85\u8fc7\u56db\u4e2a\u5173\u952e\u8bcd\uff09')),
                ('description', models.TextField(max_length=1000, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u63a8\u5e7f\u4fe1\u606f',
                'verbose_name_plural': '\u63a8\u5e7f\u4fe1\u606f',
            },
        ),
    ]
