# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-25 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import index.util


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_spider_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='/static/imgs/canada.jpg', upload_to=index.util.upload_video_cover, verbose_name='\u5c01\u9762\u56fe\u7247'),
        ),
    ]
