# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-30 16:39
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_article_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('content', DjangoUeditor.models.UEditorField(max_length=100000, verbose_name='\u5185\u5bb9')),
                ('country', models.IntegerField(choices=[(1, '\u6fb3\u5927\u5229\u4e9a'), (2, '\u65b0\u897f\u5170'), (3, '\u52a0\u62ff\u5927')], verbose_name='\u56fd\u5bb6')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u77e5\u6089',
                'verbose_name_plural': '\u9879\u76ee\u77e5\u6089',
            },
        ),
    ]
